export const CATEGORIAS = [
  'Educação',
  'Educação Especial',
  'Estética',
  'Direito',
  'Administração',
  'Enfermagem',
  'Massagem',
  'Psicologia',
  'Engenharia',
  'HIDRÁULICA',
  'VETERINÁRIA E ZOOTECNIA',
  'MATEMÁTICA',
  'ESTATUTO',
  'Nutrição',
  'Segurança',
  'Manicure/Pedicure',
  'Cosmetologia',
  'Terapia Holística',
  'Serviços Gerais',
  'Motorista',
  'Cuidador de Idosos',
  'Setor Imobiliário',
  'Informática',
  'Idiomas',
  'VENDAS',
  'ESPECIALIZAÇÃO TÉCNICA',
];
