import "reflect-metadata";
import { initializeDataSource } from "../src/lib/data-source";
import { Cursos } from "../src/database/entities/cursos.entity";

const categoria = "DIREITO";

const conteudoPadrao = JSON.stringify([
  "Fundamentos jurídicos e conceitos essenciais",
  "Legislação e normas aplicáveis",
  "Análise de casos e jurisprudência",
  "Procedimentos e práticas profissionais",
  "Ética, cidadania e direitos fundamentais",
  "Aplicações práticas no contexto jurídico"
]);

const listaBruta = `
1. DNA FORENSE
2. DOCUMENTOSCOPIA
3. EDUCAÇÃO EM DIREITOS HUMANOS
4. EMPODERAMENTO FEMININO
5. ENFERMAGEM FORENSE
6. ENFRENTAMENTO AO TRABALHO ESCRAVO
7. ENGENHARIA SOCIAL
8. ESCREVENTE EXTRA-JUDICIAL
9. ESTATUTO DA CRIANÇA E DO ADOLESCENTE (ECA)
10. ESTATUTO DA IGUALDADE RACIAL - LEI 12.288
1. ESTATUTO JUVENTUDE (LEI - 12.852)
2. ESTATUTO DA PESSOA COM DEFICIÊNCIA
3. ESTATUTO DA PESSOA COM DEFICIÊNCIA (LEI 13.146)
4. ESTATUTO DO DESARMAMENTO
5. ESTATUTO DO IDOSO
6. ESTATUTO DO ÍNDIO (LEI 6.001)
7. ESTATUTO DO VIGILANTE
8. ÉTICA E FORMAÇÃO CIDADÃ
9. FAMÍLIA E O SISTEMA PENITENCIÁRIO
10. FILOSOFIA DO DIREITO
1. FILOSOFIA JURÍDICA
2. FORMAÇÃO DE CONSELHEIRO EM DIREITOS HUMANOS
3. FOTOGRAFIA FORENSE
4. FRAUDE ELEITORAL
5. GENÉTICA FORENSE
6. GERENCIAMENTO DE CRISE NO SISTEMA PRISIONAL
7. GERENCIAMENTO DE CRISE POLICIAL
8. GESTÃO DE CONTRATOS PÚBLICOS
9. GESTÃO DE CRISE, COMUNICAÇÃO E NEGOCIAÇÃO
10. GESTÃO DE ESCRITÓRIO DE ADVOCACIA
1. GESTÃO DE POLÍTICAS PÚBLICAS DE DIREITOS HUMANOS
2. GESTÃO JURÍDICA
3. GESTÃO JURÍDICA EMPRESARIAL
4. GRAFOLOGIA
5. GRAFOSCOPIA
6. HERMENÊUTICA CONSTITUCIONAL
7. HERMENÊUTICA JURÍDICA
8. IDENTIFICAÇÃO DE PIRÂMIDES FINANCEIRAS
9. IGUALDADE RACIAL
10. IMIGRAÇÃO E A CRISE DOS REFUGIADOS
1. IMPROBIDADE ADMINISTRATIVA
2. INICIAÇÃO A ADVOCACIA
3. INTELIGÊNCIA PENITENCIÁRIA
4. INVESTIGAÇÃO CIBERNÉTICA
5. INVESTIGAÇÃO CRIMINAL
6. INVESTIGAÇÃO DE FRAUDES CORPORATIVAS
7. INVESTIGAÇÃO DIGITAL
8. INVESTIGAÇÃO PATRIMONIAL
9. JUIZ DA PAZ
10. JURIMETRIA
1. LATIM JURÍDICO
2. LEGISLAÇÃO AMBIENTAL BRASILEIRA
3. LEGISLAÇÃO CONDOMINIAL
4. LEGISLAÇÃO DE SEGURANÇA PRIVADA LEGISLAÇÃO E DIREITOS DO PACIENTE
5. LEGISLAÇÃO EDUCACIONAL
6. LEGISLAÇÃO ESPORTIVA
7. LEGISLAÇÃO ESTÉTICA
8. LEGISLAÇÃO SOCIAL E DIREITOS HUMANOS
9. LEGISLAÇÃO TRABALHISTA
10. LEGISLAÇÃO, POLÍTICAS E DIREITOS DA PESSOA SURDA
1. LEI 8.742 (LOAS)
2. LEI ANTIRRACISTA (LEI 7.716)
3. LEI BERENICE PIANA (LEI 12.764)
4. LEI BRASILEIRA DE INCLUSÃO (LBI)
5. LEI DA FICHA LIMPA
6. LEI DE COTAS
7. LEI DE DIRETRIZES ORÇAMENTÁRIAS (LDO)
8. LEI DE RESPONSABILIDADE FISCAL (LRF)
9. LEI DE INQUILINATO (LEI 8.245)
10. LEI DOS MEDICAMENTOS GENÉRICOS (LEI N. 9.787)
1. LEI GERAL DE PROTEÇÃO DE DADOS (LGPD)
2. LEI LUCAS (LEI 13.722)
3. LEI MARIA DA PENHA (LEI 11.340)
4. LEI ORÇAMENTÁRIA ANUAL (LOA)
5. LEI SECA (LEI 11.705)
6. LEILÃO DE IMÓVEIS
7. MEDIAÇÃO JUDICIAL E EXTRAJUDICIAL
8. MEDICINA LEGAL
9. MEDIDA PROTETIVA À VÍTIMA DE VIOLÊNCIA DOMÉSTICA
10. MEDIDAS DE PROTEÇÃO À CRIANÇA E AO ADOLESCENTE
1. MEDIDAS DE PROTEÇÃO AO IDOSO
2. MEDIDAS PROTETIVAS DE URGÊNCIA À MULHER
3. MEDIDAS SOCIOEDUCATIVAS
4. MEDIDAS SOCIOEDUCATIVAS APLICADAS AO JOVEM INFRATOR
5. MENORIDADE PENAL E CRIMINALIDADE
6. MIGRAÇÃO E DIREITOS HUMANOS
7. NOÇÕES BÁSICAS DE PERÍCIA JUDICIAL AMBIENTAL
8. NOÇÕES BÁSICAS DE PERÍCIA TRABALHISTA
9. NOÇÕES DE AUDITORIA AMBIENTAL PÚBLICA
10. NOÇÕES DE DIREITO PÚBLICO
1. O PAPEL DO SERVIÇO SOCIAL NO SISTEMA PENITENCIÁRIO
2. ODONTOLOGIA FORENSE
3. OUVIDORIA JUDICIÁRIA
4. PAPILOSCOPIA
5. PARTICIPAÇÃO SOCIAL E CIDADANIA
6. PATOLOGIA FORENSE
7. PEDAGOGIA JURÍDICA
8. PERÍCIA AMBIENTAL
9. PERÍCIA CONTÁBIL BÁSICA
10. PERÍCIA DIGITAL BÁSICA
1. PERÍCIA EM DOCUMENTOS
2. PERÍCIA EM INCÊNDIOS E EXPLOSÕES
3. PERÍCIA FORENSE BÁSICA
4. PERÍCIA FORENSE COMPUTACIONAL
5. PERÍCIA GRAFOTÉCNICA
6. PERÍCIA JUDICIAL BÁSICA
7. PERÍCIA TOXICOLÓGICA
8. PERÍCIA TRABALHISTA BÁSICA
9. PERÍCIA VEICULAR
10. PLANEJAMENTO PREVIDENCIÁRIO
1. PRÁTICA JURÍDICA
2. PREVENÇÃO À FRAUDE DIGITAL
3. PREVENÇÃO À FRAUDE FINANCEIRA
4. PREVENÇÃO A FRAUDES DOCUMENTAIS
5. PREVENÇÃO À LAVAGEM DE DINHEIRO
6. PREVIDÊNCIA COMPLEMENTAR
7. PROCESSO CIVIL
8. PROCESSO DE ADOÇÃO DE CRIANÇAS E ADOLESCENTES
9. PROPRIEDADE INTELECTUAL
10. PROTESTO DE TÍTULOS
1. PSICOLOGIA CRIMINAL
2. PSICOLOGIA FORENSE
3. PSICOLOGIA JURÍDICA
4. PSIQUIATRA FORENSE
5. QUÍMICA FORENSE
6. RACISMO ESTRUTURAL E SELETIVIDADE PENAL
7. RADIOLOGIA FORENSE
8. REGIME GERAL DE PREVIDÊNCIA SOCIAL (RGPS)
9. REGISTRO CIVIL DE PESSOAS NATURAIS E JURÍDICAS
10. REGISTRO DE IMÓVEIS
`;

function extrairNomesDaLista(lista: string): string[] {
  return [
    ...new Set(
      lista
        .split("\n")
        .map((linha) => linha.trim())
        .filter((linha) => linha.length > 0)
        .filter((linha) => /^\d+\./.test(linha))
        .map((linha) => linha.replace(/^\d+\.\s*/, "").trim())
    )
  ];
}

async function seedDireitoLote20260309() {
  try {
    const ds = await initializeDataSource();
    const cursosRepo = ds.getRepository(Cursos);

    const nomes = extrairNomesDaLista(listaBruta);
    let criados = 0;
    let existentes = 0;

    for (const nome of nomes) {
      const cursoExistente = await cursosRepo.findOne({ where: { nome } });

      if (cursoExistente) {
        existentes += 1;
        console.log(`JA EXISTE: ${nome}`);
        continue;
      }

      const curso = cursosRepo.create({
        nome,
        duracao: 30,
        categoria,
        conteudo: conteudoPadrao
      });

      await cursosRepo.save(curso);
      criados += 1;
      console.log(`CRIADO CURSO: ${nome}`);
    }

    console.log("\nLOTE DE DIREITO 20260309 PROCESSADO COM SUCESSO!");
    console.log(`TOTAL NA LISTA (SEM NUMERACAO/DUPLICATAS): ${nomes.length}`);
    console.log(`CRIADOS: ${criados}`);
    console.log(`JA EXISTENTES: ${existentes}`);

    process.exit(0);
  } catch (error) {
    console.error("ERRO AO PROCESSAR LOTE DE DIREITO 20260309:", error);
    process.exit(1);
  }
}

seedDireitoLote20260309();
