import "reflect-metadata";
import { initializeDataSource } from "../src/lib/data-source";
import { Cursos } from "../src/database/entities/cursos.entity";

const categoriaEducacaoFisica = "EDUCAÇÃO FÍSICA E ESPORTES";

const conteudoPadrao = JSON.stringify([
  "Fundamentos e conceitos da área",
  "Técnicas e metodologias aplicadas",
  "Boas práticas de segurança e atendimento",
  "Planejamento e avaliação do treinamento",
  "Aplicações práticas e estudos de caso"
]);

const nomesEducacaoFisica = [
  "ACESSIBILIDADE NO ESPORTE",
  "ALONGAMENTO E DESEMPENHO ESPORTIVO",
  "ALONGAMENTO NA TERCEIRA IDADE",
  "ALONGAMENTO PARA PREVENÇÃO DE LESÕES",
  "ANALISTA DE DESEMPENHO DE FUTEBOL",
  "ANALISTA DE DESEMPENHO ESPORTIVO",
  "ANALISTA DE FUTEBOL",
  "ANTROPOMETRIA",
  "APRENDIZAGEM MOTORA",
  "AQUECIMENTO E ALONGAMENTO",
  "ARBITRAGEM DE BASQUETE",
  "ARBITRAGEM DE BOXE",
  "ARBITRAGEM DE CAPOEIRA",
  "ARBITRAGEM DE CICLISMO",
  "ARBITRAGEM DE FUTEBOL",
  "ARBITRAGEM DE FUTSAL",
  "ARBITRAGEM DE HANDEBOL",
  "ARBITRAGEM DE JIU-JITSU",
  "ARBITRAGEM DE JUDÔ",
  "ARBITRAGEM DE KARATÊ",
  "ARBITRAGEM DE NATAÇÃO",
  "ARBITRAGEM DE SKATE",
  "ARBITRAGEM DE TAEKWONDO",
  "ARBITRAGEM DE VOLEIBOL",
  "ARBITRAGEM ESPORTIVA",
  "ÁRBITRO DE FUTSAL",
  "ATIVIDADE FÍSICA E PREVENÇÃO DE DOENÇAS CRÔNICAS",
  "ATIVIDADE FÍSICA E RENDIMENTO ESCOLAR",
  "ATIVIDADE FÍSICA E SAÚDE MENTAL",
  "ATIVIDADE FÍSICA NA TERCEIRA IDADE",
  "ATIVIDADE FÍSICA NO PRESÍDIO",
  "AUXILIAR DE ACADEMIA",
  "AUXILIAR DE ESPORTES E LAZER",
  "AVALIAÇÃO FÍSICA",
  "AVALIAÇÃO FISIOTERAPÊUTICA NO ESPORTE",
  "BIBLIOTERAPIA",
  "BIOMECÂNICA",
  "BIOMECÂNICA NO DESENVOLVIMENTO HUMANO",
  "BOAS PRÁTICAS NA EDUCAÇÃO FÍSICA ESCOLAR",
  "BODYBUILDING",
  "CARDIOLOGIA DO ESPORTE",
  "CINESIOLOGIA",
  "COACH ESPORTIVO",
  "COMPETIÇÃO E ESPORTE",
  "CONDICIONAMENTO FÍSICO",
  "CORRUPÇÃO NO ESPORTE",
  "CRIMINALIZAÇÃO DAS TORCIDAS ORGANIZADAS",
  "DESENVOLVIMENTO FÍSICO E ESPORTIVO",
  "EDUCAÇÃO FÍSICA NA ESCOLA",
  "ELETROESTIMULAÇÃO",
  "ESPORTE COMO PROPOSTA PEDAGÓGICA",
  "ESPORTE DE RENDIMENTO",
  "ESPORTE EDUCACIONAL",
  "ÉTICA NO ESPORTE",
  "EXERCÍCIO FÍSICO E PREVENÇÃO DE DOENÇAS",
  "EXERCÍCIO FÍSICO E QUALIDADE DE VIDA",
  "EXERCÍCIO FÍSICO E SAÚDE MENTAL",
  "EXERCÍCIO FÍSICO NA GESTAÇÃO",
  "EXERCÍCIOS AQUÁTICOS E SEUS BENEFÍCIOS",
  "FISICULTURISMO",
  "FISIOLOGIA DO ESPORTE",
  "FISIOLOGIA DO EXERCÍCIO",
  "FISIOTERAPIA ESPORTIVA",
  "FLEXIBILIDADE E ALONGAMENTO",
  "FUNDAMENTOS DO KARATÊ",
  "FUNDAMENTOS TÉCNICOS E TÁTICOS DO FUTEBOL",
  "FUTEBOL DE BASE",
  "FUTEBOL E VIOLÊNCIA",
  "GANDULA",
  "GERENCIAMENTO DE SEGURANÇA EM ESTÁDIOS DE FUTEBOL",
  "GERENTE DE ACADEMIA",
  "GESTÃO DE CLUBES DE FUTEBOL",
  "GESTÃO DE ESCOLINHA DE FUTEBOL",
  "GESTÃO DE EVENTOS ESPORTIVOS",
  "GESTÃO DESPORTIVA E DE LAZER",
  "GESTÃO ESPORTIVA",
  "GESTÃO FINANCEIRA NO ESPORTE",
  "GESTOR ESPORTIVO",
  "GINÁSTICA LABORAL",
  "GOLEIRO DE FUTEBOL",
  "GOLEIRO DE FUTSAL",
  "GOVERNANÇA NO ESPORTE",
  "HIDROGINÁSTICA E SAÚDE FÍSICA",
  "HISTÓRIA DO FUTEBOL",
  "INCLUSÃO DE CRIANÇAS COM DEFICIÊNCIA NO ESPORTE",
  "INFLUÊNCIA DA NATAÇÃO NO DESENVOLVIMENTO INFANTIL",
  "INICIAÇÃO AO FUTSAL",
  "INICIAÇÃO ESPORTIVA INFANTIL",
  "INSTRUTOR DE CROSSFIT",
  "INSTRUTOR DE FUTEBOL",
  "INSTRUTOR DE JIU JITSU",
  "INSTRUTOR DE MUSCULAÇÃO",
  "INSTRUTOR DE NATAÇÃO",
  "JOGOS ESCOLARES E COMPETIÇÃO",
  "JORNALISMO ESPORTIVO",
  "LEGISLAÇÃO ESPORTIVA",
  "LIDERANÇA NO ESPORTE",
  "LOGÍSTICA DESPORTIVA",
  "MAQUEIRO ESPORTISTA",
  "MARKETING ESPORTIVO",
  "MASSAGEM DESPORTIVA",
  "METODOLOGIA DOS ESPORTES COLETIVOS",
  "MONITOR DE ESPORTES E LAZER",
  "MONITOR DE RECREAÇÃO INFANTIL",
  "MONITOR ESPORTIVO",
  "MORFOLOGIA E SINTAXE",
  "MUSCULAÇÃO NA TERCEIRA IDADE",
  "NEUROCIÊNCIA NO ESPORTE",
  "NEUROFISIOLOGIA",
  "NEUROPERFORMANCE",
  "NUTRIÇÃO E SAÚDE MENTAL DO ATLETA",
  "NUTRIÇÃO ESPORTIVA",
  "NUTRIÇÃO NO ESPORTE",
  "OLHEIRO DE FUTEBOL",
  "OVERTRAINING E SEUS EFEITOS",
  "PARATLETISMO E INCLUSÃO",
  "PEDAGOGIA DA COOPERAÇÃO",
  "PEDAGOGIA DO ESPORTE",
  "PEDAGOGIA HOSPITALAR",
  "PERSONAL TRAINER",
  "PESSOAS COM DEFICIÊNCIA E INCLUSÃO ESPORTIVA",
  "POLÍTICA ANTIDOPING",
  "PREPARADOR FÍSICO DE FUTEBOL",
  "PREPARADOR FÍSICO DE FUTSAL",
  "PRIMEIROS SOCORROS NO ESPORTE",
  "PROFESSOR DE ESCOLINHA DE FUTEBOL",
  "PROGRAMA BOLSA ATLETA",
  "PSICOLOGIA DO ESPORTE",
  "PSICOLOGIA DO ESPORTE APLICADA À INFÂNCIA",
  "PSICOLOGIA DO TREINADOR",
  "PSICOMOTRICIDADE",
  "RACISMO NO FUTEBOL",
  "RECEPCIONISTA DE ACADEMIA",
  "RISCO DOS ANABOLIZANTES PARA A SAÚDE",
  "SAÚDE CARDÍACA EM ATLETAS",
  "SEGURANÇA EM EVENTOS ESPORTIVOS",
  "TRANSTORNOS ALIMENTARES NO ESPORTE",
  "TREINADOR DE BASQUETE",
  "TREINADOR DE FUTEBOL",
  "TREINADOR DE FUTSAL",
  "TREINADOR DE GOLEIROS",
  "TREINADOR DE HANDEBOL",
  "TREINADOR DE JIU-JITSU",
  "TREINADOR DE KARATÊ",
  "TREINADOR DE NATAÇÃO",
  "TREINADOR DE TAEKWONDO",
  "TREINADOR DE VOLEIBOL",
  "TREINAMENTO DE FORÇA",
  "TREINAMENTO ESPORTIVO",
  "TREINAMENTO FUNCIONAL",
  "TURISMO ESPORTIVO",
  "VALORES NO ESPORTE",
  "VIOLÊNCIA NO ESPORTE"
];

const cursosEducacaoFisica = nomesEducacaoFisica.map((nome) => ({
  nome,
  categoria: categoriaEducacaoFisica,
  conteudo: conteudoPadrao
}));

async function seedCursosEducacaoFisica() {
  console.log(` Iniciando seed da categoria ${categoriaEducacaoFisica}...`);

  try {
    const dataSource = await initializeDataSource();
    const cursoRepository = dataSource.getRepository(Cursos);

    console.log(" Verificando cursos existentes...");

    for (const cursoData of cursosEducacaoFisica) {
      const existente = await cursoRepository.findOne({
        where: { nome: cursoData.nome }
      });

      if (existente) {
        console.log(`  Curso já existe: ${cursoData.nome}`);
        continue;
      }

      const curso = cursoRepository.create(cursoData);
      await cursoRepository.save(curso);
      console.log(` Criado curso: ${cursoData.nome}`);
    }

    console.log(`\n Categoria ${categoriaEducacaoFisica} criada com sucesso!`);
    console.log(` ${cursosEducacaoFisica.length} cursos adicionados!`);
    process.exit(0);
  } catch (error) {
    console.error(" Erro ao criar cursos:", error);
    process.exit(1);
  }
}

seedCursosEducacaoFisica();
