import "reflect-metadata";
import { initializeDataSource } from "../src/lib/data-source";
import { Cursos } from "../src/database/entities/cursos.entity";

const categoria = "ENFERMAGEM";

const conteudoPadrao = JSON.stringify([
  "Fundamentos e conceitos introdutórios",
  "Protocolos e rotinas assistenciais",
  "Planejamento e organização do cuidado",
  "Segurança do paciente e biossegurança",
  "Comunicação em equipe multiprofissional",
  "Aplicações práticas em saúde"
]);

const listaBruta = `
1. A IMPORTÂNCIA DO ALEITAMENTO MATERNO
2. ACOLHIMENTO EM SAÚDE MENTAL
3. ACOLHIMENTO HUMANIZADO
4. ACOMPANHAMENTO DO DESENVOLVIMENTO INFANTIL
5. ADMINISTRAÇÃO EM ENFERMAGEM
6. APERFEIÇOAMENTO EM CUIDADOS PALIATIVOS
7. APERFEIÇOAMENTO PARA CUIDADORES DE IDOSOS
8. ARMAZENAMENTO DE MEDICAMENTOS
9. ASSISTÊNCIA BÁSICA À GESTANTE
10. ASSISTÊNCIA DE ENFERMAGEM AO PACIENTE ACAMADO
1. ASSISTÊNCIA DE ENFERMAGEM AO PACIENTE ONCOLÓGICO
2. ASSISTÊNCIA DE ENFERMAGEM AO PACIENTE PSIQUIÁTRICO
3. ATENÇÃO À GESTANTE NO SUS
4. ATENÇÃO À SAÚDE DO RECÉM-NASCIDO
5. ATENÇÃO AO IDOSOS COM DEMÊNCIA
6. ATENÇÃO PRÉ-NATAL E PUERPERAL
7. ATENDIMENTO HUMANIZADO NA SAÚDE
8. ATENDIMENTO PRÉ-HOSPITALAR
9. AUTISMO E ENFERMAGEM
10. AUXILIAR DE ANÁLISES CLÍNICAS
1. AUXILIAR DE COLETA DE EXAMES LABORATORIAIS
2. AUXILIAR DE LABORATÓRIO
3. AVALIAÇÃO E TRATAMENTO DE FERIDAS
4. BIOÉTICA NA ENFERMAGEM
5. BIOSSEGURANÇA EM SALA DE VACINA
6. BIOSSEGURANÇA EM ENFERMAGEM
7. BOAS PRÁTICAS DE ARMAZENAMENTO E DISTRIBUIÇÃO DE MEDICAMENTOS
8. BOAS PRÁTICAS DE DISPENSAÇÃO DE MEDICAMENTOS
9. BOAS PRÁTICAS FARMACÊUTICAS
10. BOAS PRÁTICAS NO LACTÁRIO HOSPITALAR
1. CAPACITAÇÃO DE PROFISSIONAIS DA SAÚDE
2. CAPACITAÇÃO EM SAÚDE DA PESSOA IDOSA
3. CÓDIGO DE ÉTICA DA ENFERMAGEM
4. CONDUTOR SOCORRISTA
5. CONTROLE DE ESTOQUE DE MEDICAMENTOS
6. CONTROLE DE QUALIDADE DE MEDICAMENTOS
7. CUIDADO COM PACIENTES IDOSOS
8. CUIDADOR DE CRIANÇAS AUTISTAS
9. CUIDADOR DE IDOSO ACAMADO
10. CUIDADOR DE IDOSO COM ALZHEIMER
1. CUIDADOR DE PESSOAS COM DEFICIÊNCIA E NECESSIDADES ESPECIAIS
2. CUIDADOR DE PESSOAS SORO POSITIVO
3. CUIDADOS COM PACIENTES AUTISTAS
4. CUIDADOS COM PACIENTES PEDIÁTRICOS
5. CUIDADOS COM PACIENTES COM HIV
6. CUIDADOS DE ENFERMAGEM AO PACIENTE CIRÚRGICO
7. CUIDADOS DE ENFERMAGEM COM PACIENTE ESQUIZOFRÊNICO
8. CUIDADOS DE ENFERMAGEM COM RN PREMATURO
9. CUIDADOS DE ENFERMAGEM EM UTI NEONATAL E PEDIÁTRICA
10. CUIDADOS PALIATIVOS
1. CUIDADOS PALIATIVOS PARA IDOSOS
2. DESENVOLVIMENTO DO BEBÊ PREMATURO
3. DIETOTERAPIA E NUTRIÇÃO
4. DISPENSAÇÃO DE MEDICAMENTOS
5. DOENÇA DE ALZHEIMER (DA)
6. DOENÇAS EMERGENTES E REEMERGENTES
7. DOENÇAS SEXUALMENTE TRANSMISSÍVEIS
8. EDUCAÇÃO TERAPÊUTICA DO PACIENTE
9. EMERGÊNCIA EM SAÚDE PÚBLICA
10. ENFERMAGEM DO TRABALHO
1. ENFERMAGEM E PACIENTES COM PNEUMONIA
2. ENFERMAGEM E SAÚDE MENTAL
3. ENFERMAGEM EM HOME CARE
4. ENFERMAGEM EM UNIDADE DE TERAPIA INTENSIVA
5. ENFERMAGEM EM URGÊNCIA E EMERGÊNCIA
6. ENFERMAGEM FORENSE
7. ENFERMAGEM INTEGRATIVA
8. ENFERMAGEM NA SAÚDE COLETIVA
9. ENFERMAGEM OBSTÉTRICA BÁSICA
10. ENFERMAGEM PREVENTIVA
1. EPIDEMIA DE DENGUE
2. ÉTICA DOS PROFISSIONAIS DE ENFERMAGEM
3. FARMACOVIGILÂNCIA HOSPITALAR
4. FATORES DE CUIDADO COM A CRIANÇA AUTISTA
5. FISCALIZAÇÃO SANITÁRIA DE MEDICAMENTOS
6. FORMAÇÃO PROFISSIONAL EM SAÚDE
7. FUNDAMENTOS DE ENFERMAGEM
8. GERENCIAMENTO DE RSS
9. GESTAÇÃO DE ALTO RISCO
10. GESTÃO DE FLUXO DE PACIENTES
1. GESTÃO DE MEDICAMENTOS EM HOSPITAIS
2. GESTÃO DE MEDICAMENTOS NO SUS
3. GESTÃO DE MEDICAMENTOS PARA IDOSOS
4. GESTÃO DE MEDICAMENTOS VENCIDOS E DESCARTES
5. GESTÃO DE RESÍDUOS DE SERVIÇOS DE SAÚDE
6. HOME CARE
7. HOSPEDARIA HOSPITALAR
8. IMPORTÂNCIA DO ACOMPANHAMENTO PRÉ-NATAL
9. INTERPRETAÇÃO DE EXAMES LABORATORIAIS
10. INTOXICAÇÃO POR MEDICAMENTOS
1. LACTARISTA
2. LEGISLAÇÃO E DIREITOS DO PACIENTE
3. LOGÍSTICA HOSPITALAR
4. MANEJO CLÍNICO DA FEBRE AMARELA
5. MANEJO CLÍNICO DA PESSOA COM CHIKUNGUNYA
6. MANEJO DA DOR PÓS-OPERATÓRIO
7. MANUSEIO DE CADÁVERES E PREVENÇÃO DE DOENÇAS
8. NOÇÕES DE PRIMEIROS SOCORROS
9. NOTIFICAÇÃO DE EVENTOS ADVERSOS
10. OBESIDADE NA INFÂNCIA E ADOLESCÊNCIA
1. OSTEOPATIA
2. PACIENTE PÓS-OPERATÓRIO E CUIDADOS DE ENFERMAGEM
3. PRÁTICAS DE AUTOCUIDADO PARA PROFISSIONAIS DA SAÚDE
4. PREVENÇÃO DA LEPTOSPIROSE
5. PREVENÇÃO DE ACIDENTES DOMÉSTICOS
6. PREVENÇÃO DO SUICÍDIO
7. PREVENÇÃO E CONTROLE DA LEISHMANIOSE
8. PRIMEIROS SOCORROS
9. PRIMEIROS SOCORROS INFANTIL
10. PROCEDIMENTOS TÉCNICOS EM SALA DE VACINA
1. PSICOLOGIA PERINATAL
2. PSICOMOTRICIDADE EM AMBIENTE HOSPITALAR
3. RADIOTERAPIA BÁSICA
4. SAÚDE COLETIVA
5. SAÚDE DA MULHER
6. SEGURANÇA DO PACIENTE
7. SEGURANÇA DO TRABALHO NA ENFERMAGEM
8. SUPERDOSAGEM DE MEDICAMENTOS
9. SUPORTE BÁSICO DE VIDA (BLS)
10. TOXICOLOGIA DE MEDICAMENTOS
1. TRABALHO EM EQUIPE NO SETOR DE SAÚDE
2. TRANSPORTE INTRA-HOSPITALAR DE PACIENTES
3. TRIAGEM E CLASSIFICAÇÃO DE RISCO
4. URGÊNCIA E EMERGÊNCIA
5. URGÊNCIAS E EMERGÊNCIAS PSIQUIÁTRICAS
6. VACINAÇÃO CONTRA DENGUE
`;

function extrairNomesDaLista(lista: string): string[] {
  const nomes = lista
    .split("\n")
    .map((linha) => linha.trim())
    .filter((linha) => linha.length > 0)
    .filter((linha) => /^\d+\./.test(linha))
    .map((linha) => linha.replace(/^\d+\.\s*/, "").trim());

  return [...new Set(nomes)];
}

async function seedEnfermagemLote() {
  try {
    const ds = await initializeDataSource();
    const cursosRepo = ds.getRepository(Cursos);

    const nomes = extrairNomesDaLista(listaBruta);
    let criados = 0;
    let existentes = 0;

    for (const nome of nomes) {
      const cursoExistente = await cursosRepo.findOne({ where: { nome } });

      if (cursoExistente) {
        existentes += 1;
        console.log(`⏭️  Já existe: ${nome}`);
        continue;
      }

      const curso = cursosRepo.create({
        nome,
        duracao: 30,
        categoria,
        conteudo: conteudoPadrao
      });

      await cursosRepo.save(curso);
      criados += 1;
      console.log(`✅ Criado curso: ${nome}`);
    }

    console.log("\n🎉 Lote de ENFERMAGEM processado com sucesso!");
    console.log(`📌 Total na lista (sem numeração/duplicatas): ${nomes.length}`);
    console.log(`✅ Criados: ${criados}`);
    console.log(`⏭️  Já existentes: ${existentes}`);

    process.exit(0);
  } catch (error) {
    console.error("❌ Erro ao processar lote de ENFERMAGEM:", error);
    process.exit(1);
  }
}

seedEnfermagemLote();
